name: Mac Application Build (PyInstaller)

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-mac-app:
    runs-on: macos-latest  # Use a Mac runner provided by GitHub

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Mac App with PyInstaller
        run: |
          # The command to build the Mac .app executable
          pyinstaller --onefile --windowed --name "Bin2Book" \
          --icon "app_logo.icns" \
          --collect-all "pypdf" \
          --collect-all "undetected_chromedriver" \
          --hidden-import "selenium.webdriver.chrome.service" \
          --hidden-import "reportlab.graphics.shapes" \
          --hidden-import "reportlab.pdfbase.pdfmetrics" \
          "gui.py"

      - name: Archive and Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bin2Book-Mac-App
          # The file to be uploaded is the executable from the dist folder
          path: dist/Bin2Book